apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edu12-3
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: .
    repoURL: https://github.com/shclub/edu12-frontend-gitops.git
    targetRevision: HEAD
  destination:
    name: mint
    namespace: default
  syncPolicy:
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=true
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=false
      - RespectIgnoreDifferences=false
